### ISSUE TITLE
Proposal: Adding a DomainDispatcher

### ISSUE THREAD

**Issue by espositofulvio** [ashleysommer/sanic-dispatcher#1]
My proposal is to add a second dispatcher object called DomainDispatcher that can route requests to different apps that can be registered dynamically, something like this:

```python
app = Sanic( 'MultiSiteApp' )
dispatcher = DomainDispatcher( app )
blog1 = Sanic( 'MyFirstBlog' )
blog2 = Sanic( 'MySecondBlog' )

dispatcher.add_app( blog1, [ 'www.blog1.com' ] )
dispatcher.add_app( blog2, [ 'www.blog2.com' ] )

if __name__ == '__main__':
  app.run( host = '0.0.0.0', port = 80 )

```
If you are interested, I can actually work on this and send a pull request in a few days.

**Comment by ashleysommer** [comment]
Host-specific routing is already built into the stock Sanic router.

An example from the docs:
```
@app.route('/id', methods=['GET'], host='example.com')
async def get_handler(request):
	return text('GET request - {}'.format(request.args))

# if the host header doesn't match example.com, this route will be used
@app.route('/id', methods=['GET'])
async def get_handler(request):
	return text('GET request in default - {}'.format(request.args))
```
Is that the functionality you want? Or do you want this functuonality on the pre-router level, so it can call into different Sanic apps based on the host?

**Comment by espositofulvio** [comment]
Yep, I was aware of the host param on the route decorator, but I was actually looking for something that could allow me to serve multiple website with different configuration. For example, I could have two blogs at different domains with a unified admin interface where I can write posts for the first, the second or both. There's an example of a subdomain dispatcher for flask here http://flask.pocoo.org/docs/0.12/patterns/appdispatch/ just as an example (I know it's wsgi but it's just to give the idea).

**Comment by ashleysommer** [comment]
@espositofulvio 
New version 0.5.2.1 with Host-based routing is now released.

You can use it similar to how you posited in your first post:
```python
app = Sanic( 'MultiSiteApp' )
dispatcher = SanicDispatcher( app )
blog1 = Sanic( 'MyFirstBlog' )
blog2 = Sanic( 'MySecondBlog' )

dispatcher.register_sanic_application( blog1, '/',  'www.blog1.com' )
dispatcher.register_sanic_application( blog2, '/',  ['www.blog2.com', 'my.blog2.org'] )

if __name__ == '__main__':
  app.run( host = '0.0.0.0', port = 80 )

```

As you can see, you still need to provide a route_prefix parameter, but it can just be `'/'` if you want catch all requests to that hostname.
You can specify a single matching hostname as a string, or multiple hostnames as an array.

**Comment by espositofulvio** [comment]
@ashleysommer well, thank you very much, that's very much appreciated :)
