### ISSUE TITLE
Will this be updated to be compatible with sanic 21.3.X+?

### ISSUE THREAD

**Issue by damianj** [ashleysommer/sanic-dispatcher#13]
I currently use this extension in a project and am looking at updating the sanic version to the latest one (currently 21.3.2). However this extension seems to be incompatible with the changes that the 21.3 release brought. The app seemingly starts fine, albeit with some warnings, but when I try to navigate to a page I get the following error.

`[2021-03-24 18:01:25 -0500] [55771] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:1234/'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sanic/http.py", line 125, in http1
    await self.protocol.request_handler(self.request)
TypeError: handle_request() missing 2 required positional arguments: 'write_callback' and 'stream_callback'
`
This is running the minimal code below

```python
from sanic import Sanic
from sanic.response import json
from sanic_dispatcher import SanicDispatcherMiddlewareController
from dta.app import dispatcher_test_app

child_apps = {
    dispatcher_test_app: "/dta"
}

app = Sanic(__name__)
dispatcher = SanicDispatcherMiddlewareController(app)

def register_multiple_sanic_applications(parent_dispatcher, sanic_apps):
    for sanic_app in sanic_apps:
        parent_dispatcher.register_sanic_application(sanic_app, sanic_apps[sanic_app], apply_middleware=True)

@app.route("/")
async def hello_world(request):
    return json({"main_app": "hello world"})

register_multiple_sanic_applications(dispatcher, child_apps)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=1234, debug=True)
```

The contents for `dta.app` from the import in the code above
```python
from sanic import Sanic
from sanic.response import json

dispatcher_test_app = Sanic(__name__)

@dispatcher_test_app.route("/")
async def dta_index(request):
    return json({"dispatcher_test_app": "hello world"})
```
    
After some minor investigation I found that simply instantiating the dispatcher (i.e., not registering any applications afterwards), `dispatcher = SanicDispatcherMiddlewareController(app)`, causes this behavior so I am fairly certain it is the cause of the error I am getting.

**Comment by ashleysommer** [comment]
Hi @damianj 
To be honest I didn't think anyone was using this.
Thanks for keeping it alive.
I know it doesn't work on 21.3, but I thought it also didn't work on 20.12LTS or any of the 20.x series. I actually thought the last version of Sanic this works on is v18.12 (or maybe 19.9).
What version of Sanic were you using before you upgarded to 21.3?

Anyway, if at least one person is using it, I will update it :)
I will try to find some time today to get it working correctly on all 3: 19.12, 20.12, and 21.3.

**Comment by damianj** [comment]
Yes, I hadn't upgraded the Sanic version for a while but it seems to at least work with Sanic 20.3 as that is the version currently installed on our server. After that I held back updating the Sanic package since I saw some bigger changes were on their way (which are now here with 21.3).

Thanks, I appreciate you maintaining this as it has helped us further modularize our project.

**Comment by ashleysommer** [comment]
@damianj 
I've pushed a new Sanic-Dispatcher release (v0.8.0)
Can you please try that to see if it works in your application?
Thanks.

**Comment by ashleysommer** [comment]
Fixed by https://github.com/ashleysommer/sanic-dispatcher/commit/4993938e0e8fe8af81229d74b4b995fcb17250e6

**Comment by damianj** [comment]
@ashleysommer 
Yes, the update has fixed the problem and the application is running again. Thank you.
