### ISSUE TITLE
Add unregister_application

### ISSUE THREAD

**Issue by espositofulvio** [ashleysommer/sanic-dispatcher#2]
As explained in https://github.com/channelcat/sanic/issues/581, I believe having an unregister_application would be a very convenient way to use sanic apps as dynamically loadable modules in a web application.

**Comment by ashleysommer** [comment]
This has been added in v0.5.2.0
You can do `unregister_application(app)` to remove it based on the app, or you can do `unregister_prefix('/my_prefix')` to unregister an application based on the Url prefix.

**Comment by ashleysommer** [comment]
Closed via https://github.com/ashleysommer/sanic-dispatcher/commit/e5f1a116c6a169e3bb2549e42161ae0b8db4c20e
