### ISSUE TITLE
Sanic-to-WSGI adapter Example

### ISSUE THREAD

**Issue by Miserlou** [ashleysommer/sanic-dispatcher#4]
The project claims to be a Sanic-to-WSGI adapter, I'd love to see a trivial example of that in the documentation. 

Is there a "pass-through" dispatcher that doesn't touch the routes? I simply want to use Sanic behind gunicorn or Zappa or whatever WSGI server I want, nothing more. Can I do that with this?

**Comment by ashleysommer** [comment]
There are two trivial examples of usage of the Sanic-to-WSGI adapter already in the README.md file.
Any time you use the `register_wsgi_application` to add an app to the `dispatcher` you are telling the dispatcher to use the Sanic-to-WSGI adapter to run that invoke that application.

Copied from the README.md file:
--------
**What if the other App is a Flask App?**
```python
from flask import Flask, make_response

app = Sanic(__name__)

dispatcher = SanicDispatcherMiddlewareController(app)
flaskapp = Flask("MyFlaskApp")

# register the wsgi_app method from the flask app into the dispatcher
dispatcher.register_wsgi_application(flaskapp.wsgi_app, "/flaskprefix")

@flaskapp.route('/')
def index():
    return make_response("Hello World from Flask App")
```
Browsing to url `/flaskprefix/` will invoke the Flask App, and call the `/` route which displays "Hello World from Flask App"

**What if the other App is a Django App?**
```python
import my_django_app

app = Sanic(__name__)

dispatcher = SanicDispatcherMiddlewareController(app)
# register the django wsgi application into the dispatcher
dispatcher.register_wsgi_application(my_django_app.wsgi.application,
                                     "/djangoprefix")
```
Browsing to url `/djangoprefix/` will invoke the Django App.

**Comment by ashleysommer** [comment]
In response to your question about a passthrough; Yes!, that is possible.
Just register your application using the route_prefix `'/'` like so:

```python
from flask import Flask, make_response

app = Sanic(__name__)

dispatcher = SanicDispatcherMiddlewareController(app)
flaskapp = Flask("MyFlaskApp")

# register the wsgi_app method from the flask app into the dispatcher
dispatcher.register_wsgi_application(flaskapp.wsgi_app, "/")

@flaskapp.route('/')
def index():
    return make_response("Hello World from Flask App")
```
In this example specifying the prefix `'/'` will cause all routes to be passed into the Flask application.

**Comment by ashleysommer** [comment]
> I simply want to use Sanic behind gunicorn or Zappa or whatever WSGI server I want, nothing more. Can I do that with this?

What you need for that is a WSGI-to-Sanic adaptor, not a Sanic-to-WSGI adapter. Sanic-Dispatcher cannot do what you want in this case.

But good news! Sanic has recently been given its own gunicorn worker, which _does_ do exactly what you are asking about.
See the deployment docs for how to use it: (See under "Running via Gunicorn")
https://github.com/channelcat/sanic/blob/master/docs/sanic/deploying.md#running-via-gunicorn

**Comment by ashleysommer** [comment]
Closing due to no response in over 27 days.
