### ISSUE TITLE
host based routing doesn't work

### ISSUE THREAD

**Issue by espositofulvio** [ashleysommer/sanic-dispatcher#6]
Hi Ashley,
I finally get to use your extension for one of my project (it will be a CMS that can serve websites on multiple domains with loadable modules) but I'm afraid the host based routing doesn't work. Here's an example:

```python
from sanic import Sanic
from sanic.response import text
from sanic_dispatcher import SanicDispatcherMiddlewareController
from sanic.exceptions import NotFound

app = Sanic( 'app' )
dispatcher = SanicDispatcherMiddlewareController( app )

child_app = Sanic( 'child' )
dispatcher.register_sanic_application( child_app, '/', [ 'www.test.it' ] )

child_app2 = Sanic( 'child2' )
dispatcher.register_sanic_application( child_app2, '/', [ 'www.test.com' ] )

child_child_app2 = Sanic( 'child_child')

child_dispatcher = SanicDispatcherMiddlewareController( child_app2 )
child_dispatcher.register_sanic_application( child_child_app2, '/test' )

@child_child_app2.route( '/test' )
async def hello_child( request ):
    return text( 'hello from www.test.com/test/test')

@child_app.route( '/' )
async def hello( request ):
    return text( 'Hello from www.test.it' )

@child_app2.route( '/' )
async def hello2( request ):
    return text( 'Hello from www.test.com' )

@child_app2.route( '/test' )
async def hello_test( request ):
    return text( 'Hello from www.test.com/test' )

app.run( host = '127.0.0.1', port = 80, debug = True )
```

I changed my host file so that www.test.it and www.test.com alias localhost, if I try to point my browser at:

http://www.test.it
http://www.test.com
http://www.test.com/test
http://www.test.com/test/test

Sanic will always return exceptions.NotFound.

**Comment by espositofulvio** [comment]
I've found a fix. You told me in (#1) to have the prefix '/' anyway but that doesn't work. The following works instead:

```python
from sanic import Sanic
from sanic.response import text
from sanic_dispatcher import SanicDispatcherMiddlewareController
from sanic.exceptions import NotFound

app = Sanic( 'app' )
dispatcher = SanicDispatcherMiddlewareController( app )

child_app = Sanic( 'child' )
# note no prefix
dispatcher.register_sanic_application( child_app, '', [ 'www.test.it' ] )

child_app2 = Sanic( 'child2' )
# note no prefix
dispatcher.register_sanic_application( child_app2, '', [ 'www.test.com' ] )

child_child_app2 = Sanic( 'child_child')

child_dispatcher = SanicDispatcherMiddlewareController( child_app2 )
child_dispatcher.register_sanic_application( child_child_app2, '/test' )

@child_child_app2.route( '/test' )
async def hello_child( request ):
    return text( 'hello from www.test.com/test/test')

@child_app.route( '/' )
async def hello( request ):
    return text( 'Hello from www.test.it' )

@child_app2.route( '/' )
async def hello2( request ):
    return text( 'Hello from www.test.com' )

@child_app2.route( '/test' )
async def hello_test( request ):
    return text( 'Hello from www.test.com/test' )

app.run( host = '127.0.0.1', port = 80, debug = True )
```

**Comment by ashleysommer** [comment]
Sorry for delayed response.
Thanks for debugging this to find the solution.
It is weird that having `'/'` route did not work for you, because it works in my testing.
That is something I will have to fix in a future version.

**Comment by espositofulvio** [comment]
If it may be of help, I'm using:

Sanic 0,5,4
Sanic-dispatcher 0.5.2.1

My hunch is that by using the '/' you register 'www.domain,com/' as the app's prefix, but when you look for a prefix in the request's url such as ' www.domain.com/test ', something like the following happens:

- first you try www.domain.com/test and it doesn't match
- then you rsplit on '/' and you have www.domain.com and test as result
- then you try www.domain.com, but we have www.domain.com/ as the prefix so it doesn't match either.
- at this point NotFound is returned.

for request like 'www.domain.com/', instead, I think the problem is that path_info is originally null, so you find an application but when you build the SanicCompactURL the path is init-ed from path_info (which is null) and then when the application routing kicks in it doesn't find a route for ''.

**Comment by ashleysommer** [comment]
@espositofulvio 
I've fixed this issue, you can now use either `'/'` or `''` as the route_prefix argument and both will work the same. This issue was actually also present when using Sanic-Dispatcher the conventional way (not using host-based routing) but it was not as obvious because routes still worked.

Version 0.5.4.2 has been released with this fix.

Also fixed:
You can now do host-based routing on any port, you don't have to use port 80.
