### ISSUE TITLE
url_for and dispatched application

### ISSUE THREAD

**Issue by espositofulvio** [ashleysommer/sanic-dispatcher#7]
This is not really an issue but I was just wondering if you have any idea how to sort out url_for for a dispatched app. If we have something like:

```python
app = Sanic( 'myapp' )
sub_section = Sanic( 'sub_section' )
dispatcher = SanicDispatcherMiddlewareController( app )

dispatcher.register_sanic_application( sub_section, '/subsection' )

@sub_section.route( '/' )
def hello_sub( request ):
     return text( sub_section.url_for( 'hello_sub' ) ) # this returns '/' instead of '/subsection/'

app.run()
```
Have you had any thoughts about this or did you have any similar situation you can share about? Maybe monkey-patching url_for and walk the tree of applications might be a viable solution?

**Comment by ashleysommer** [comment]
This is something I've thought about, but I don't use `url_for()` in my applications so it has not been an issue for me. It is however actually something that I think needs to be addressed.

There are several ways this might be done, including the method you mentioned monkey-patching `url_for()` in each sub-app, or perhaps creating a different `url_for()` on the dispatcher that checks all of the sub-apps.

**Comment by ashleysommer** [comment]
This feature is now added in 0.5.4.4 :smile:!

There is a new `url_for()` method on the dispatcher controller that works as you would expect it to.
Additionally, the `url_for()` function on the parent app (the Sanic app that owns the Sanic-dispatcher controller) is patched and works as you expect it to.

in your example:
```python
app = Sanic( 'myapp' )
sub_section = Sanic( 'sub_section' )
dispatcher = SanicDispatcherMiddlewareController( app )

dispatcher.register_sanic_application( sub_section, '/subsection' )

@sub_section.route( '/' )
def hello_sub( request ):
     return text( sub_section.url_for( 'hello_sub' ) ) # this returns '/' instead of '/subsection/'

app.run()
```
You can now do:
```python
@sub_section.route( '/' )
def hello_sub1( request ):
     return text( app.url_for( 'hello_sub1' ) ) # this returns '/subsection/'
# OR
@sub_section.route( '/' )
def hello_sub2( request ):
     return text( dispatcher.url_for( 'hello_sub2' ) ) # this returns '/subsection/'
```
Closed via https://github.com/ashleysommer/sanic-dispatcher/commit/6c64ca15208390b827c64e5edfdbad6ce0964e0a

**Comment by espositofulvio** [comment]
I believe this extension is the true linchpin to build modular systems with sanic and you're making it great! Thank you very much!

**Comment by ashleysommer** [comment]
Keep the feature requests coming!
