### ISSUE TITLE
Gino not initalized error when using SanicDispatcherMiddlewareController

### ISSUE THREAD

**Issue by damianj** [ashleysommer/sanic-dispatcher#8]
### **Context**

Coming from Flask I thought I could initialize the DB in the child app and everything would be fine even after using dispatcher middle-ware since I've done this in Flask. For example in Flask with dispatcher middle-ware in the child app.py I'd do something like:
```python
with app.app_context():
    db.init_app(app)
    db.create_all()
```

Indeed everything works if I run the child sanic app on it's own, but as soon as I use the `SanicDispatcherMiddlewareController` and do `dispatcher.register_sanic_application(child_app, '/child_app', apply_middleware=True)` I get the following error when I try to query the DB (Postgresql):

### **Error**
```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sanic/app.py", line 885, in handle_request
    response = await self._run_request_middleware(request)
  File "/usr/lib/python3.7/site-packages/sanic/app.py", line 1228, in _run_request_middleware
    response = await response
  File "/usr/lib/python3.7/site-packages/gino/ext/sanic.py", line 87, in on_request
    request['connection'] = await self.acquire(lazy=True)
  File "/usr/lib/python3.7/site-packages/gino/api.py", line 481, in acquire
    return self.bind.acquire(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gino/api.py", line 501, in __getattribute__
    raise self._exception
gino.exceptions.UninitializedError: Gino engine is not initialized.
```

IF, however, I initialize the db on the parent app like:
```python
parent_app.config.DB_HOST = 'localhost'
parent_app.config.DB_PORT = '5432'
parent_app.config.DB_USER = 'some_user'
parent_app.config.DB_PASSWORD = 'some_password'
parent_app.config.DB_DATABASE = 'some_db'
parent_api_db.init_app(app)
```
instead of the child app then it works, but I'd like to have each child initializing different db's/models so this is not really a solution for me.

As far as I can tell from tracing the execution of the code the difference is that when I initialize the db on parent app the `before_server_start` listener triggers in `Gino()` and when I initialize the db on the child app it doesn't. That's as far as I've dug into the issue.

Fairly new to Sanic so some direction would be appreciated as I am not even sure if what I am trying to get to happen makes sense within the context of Sanic.

**Comment by ashleysommer** [comment]
Hi @damianj

I haven't updated Sanic-Dispatcher in a while, so there is a chance there is an incompatibility using this version of Sanic-Dispatcher on newer versions of Sanic.

There is also a chance that Sanic-Dispatcher doesn't correctly run the before_server_start listener, on the child apps. I don't think I fully tested that feature.

I will write a test to replicate this and get a fix out as soon as I can.

**Comment by damianj** [comment]
After some more investigation I ended up doing something like the following in my `app.py` (some code is irrelevant, but posted for completion in case anyone comes across this post):

```python
from functools import partial
from sanic import Sanic
from sanic_dispatcher import SanicDispatcherMiddlewareController
from child_app_1.app import child_app_1
from child_app_2.app import child_app_2

child_apps = {
    child_app_1: "/child_app_1",
    child_app_2: "/child_app_2"
}

app = Sanic(__name__)
dispatcher = SanicDispatcherMiddlewareController(app)


child_before_server_start_listeners = {
    child_app: child_app.listeners.get("before_server_start", []) for child_app in child_apps
}

child_before_server_stop_listeners = {
    child_app: child_app.listeners.get("before_server_stop", []) for child_app in child_apps
}


def register_multiple_sanic_applications(parent_dispatcher, sanic_apps):
    for sanic_app in sanic_apps:
        parent_dispatcher.register_sanic_application(sanic_app, sanic_apps[sanic_app], apply_middleware=True)


@app.listener('before_server_start')
async def child_apps_before_server_start(parent_app, loop):
    for k in child_before_server_start_listeners:
        child_listeners = [partial(listener, loop) for listener in child_before_server_start_listeners[k]]

        await k.trigger_events(child_listeners, loop)


@app.listener('before_server_stop')
async def child_apps_before_server_stop(parent_app, loop):
    for k in child_before_server_stop_listeners:
        child_listeners = [partial(listener, loop) for listener in child_before_server_stop_listeners[k]]

        await k.trigger_events(child_listeners, loop)

register_multiple_sanic_applications(dispatcher, child_apps)

if __name__ == "__main__":
    app.run(port=5000, debug=False)
```

This allowed me to define models for each app and run `db.init_app(⋯)` on each child app in it's own `app.py` which resulted in being able to successfully query the DB when hitting endpoints on each of the child applications. Also did something similar for the `before_server_stop` listeners since I saw GINO had some when I was debugging my application.

**Comment by ashleysommer** [comment]
@damianj  
I've pushed a new version of Sanic-Dispatcher, updated with better compatibility with newer sanic versions, as well as adding in the event listener compatibility hooks. Let me know if it fixes this issue.
It is v 0.7.0.0 and should be out on PyPI soon.

**Comment by ashleysommer** [comment]
Fixed by https://github.com/ashleysommer/sanic-dispatcher/commit/621c504756b389871a7ce230ae8b53cbf5ab17be
